### ISSUE TITLE
safari doesn't support ogg files, which means apps with music embedded just crash on it

### ISSUE THREAD

**Issue by increpare** [haxegon/haxegon#222]
just leaving as a note.

**Comment by TerryCavanagh** [comment]
Yeah, this one is very annoying :/ Lime has some built in functionality to overwrite the asset loading for browsers, which means I get a crash bug when an asset doesn't exist instead of an error message. Might need to do some pull requesting to sort it out: https://github.com/TerryCavanagh/haxegon/issues/189

**Comment by TerryCavanagh** [comment]
No longer an issue!
