### ISSUE TITLE
Instant crash on neko

### ISSUE THREAD

**Issue by TheSpydog** [haxegon/haxegon#241]
**Haxegon Version:** 0.11.1
**Haxe Version:** 3.4.6
**OpenFL / Lime:** 7.1.2 / 6.2.0

Running an empty template project on Windows with `lime test neko` causes the game to immediately crash with the following message:
```Called from ? line 1
Called from ApplicationMain.hx line 80
Called from ApplicationMain.hx line 112
Called from lime/app/Application.hx line 269
Called from lime/_backend/native/NativeApplication.hx line 160
Called from lime/_backend/native/NativeApplication.hx line 200
Called from lime/_backend/native/NativeApplication.hx line 713
Called from haxe/Timer.hx line 244
Called from openfl/display/Stage3D.hx line 186
Called from openfl/events/EventDispatcher.hx line 96
Called from openfl/events/EventDispatcher.hx line 217
Called from starling/core/Starling.hx line 609
Called from starling/core/Starling.hx line 376
Called from starling/core/Starling.hx line 386
Called from starling/display/DisplayObjectContainer.hx line 134
Called from starling/display/DisplayObjectContainer.hx line 448
Called from starling/display/DisplayObjectContainer.hx line 438
Called from starling/display/DisplayObject.hx line 728
Called from starling/events/EventDispatcher.hx line 137
Called from starling/events/EventDispatcher.hx line 177
Called from haxegon/Core.hx line 34
Called from haxegon/Core.hx line 56
Called from haxegon/Text.hx line 331
Called from haxegon/Text.hx line 400
Called from haxegon/Text.hx line 377
Called from haxegon/Text.hx line 345
Called from haxegon/Text.hx line 404
Called from haxegon/Text.hx line 12
Called from haxegon/Text.hx line 16
Called from haxegon/Text.hx line 42
Uncaught exception - Invalid operation (+)

**Comment by TerryCavanagh** [comment]
Oh, yep - Neko hasn't worked in ages. From what I've heard it's one its way out anyway. I'll see about getting it working for 0.13.0, though!

**Comment by TheSpydog** [comment]
Alternatively you could just put a disclaimer in the documentation that it only works with native desktop / html5 builds for the time being. Since Neko is in decline anyway, this might save you some work. :)

**Comment by TerryCavanagh** [comment]
Neko is *kinda* nice for quickly trying native builds, so it'd be nice if it did work! But yeah, I could well end up just doing a disclaimer :P

**Comment by azrafe7** [comment]
Hello there @TerryCavanagh and @TheSpydog, :hand: 
I've just discovered this lib and started playing with it (I'm actually enjoying it so far, so thanks! :+1:).

Trying it with neko lead me to this issue, so I began a little investigation, and 
looking at the reported neko errors I think I've found a way to make it work again (at least with some of the basic samples - still playing with it).

(I thought about making a PR with the proposed fixes, but then I figured I'd just post my findings, as I'm still a haxegon-noob and might be missing something important)

...and it seems it needs just two minor changes:
 1. `currenttextfield` must be initialized to -1 before being used (here  https://github.com/haxegon/haxegon/blob/430b9c06d79ce70845b55b8e602c5bed11c76e8e/haxegon/Text.hx#L71), or alternatively a call to `Fontclass.reset()` has to be made before using it 

 2. add an empty `function new()` to `Main` in any blank_project (this is because `Type.createInstance()` used here https://github.com/haxegon/haxegon/blob/430b9c06d79ce70845b55b8e602c5bed11c76e8e/haxegon/Scene.hx#L10) is only guaranteed to work if the class identified by the `cls` arg has a constructor defined (it just works for other targets, but not for neko)

Another way to fix 2. might be to use `Type.createEmptyInstance()`, but that would also [bypass the actual constructor](https://github.com/HaxeFoundation/haxe/blob/2d1e3f0e883a7257224e50f5a80fc247b9912c44/std/Type.hx#L157-L167) - if there is one - which might be counter-intuitive.

PS: It would be worth to check if similar neko-upsetting issues might be present elsewhere in the codebase.

**Comment by TerryCavanagh** [comment]
This is great, thanks @azrafe7!

Should have a 0.12.1 out tonight with neko support!

**Comment by azrafe7** [comment]
Nice!

Now that I've played a bit more with the samples I can add a 3rd point to make most of them work with neko:

 3. add ` || neko` wherever cpp conditional compilation is used (so in Gfx, Sound, and in every project.xml)

Haven't managed to make `Data.loadxml()` work though, so the geography game won't run. But still that's a good starting point, and other things can be fixed as they pop up! :+1:

**Comment by TerryCavanagh** [comment]
Yeah, just working through `Data.loadxml()` at the minute, that's a bit of a mess!

**Comment by TerryCavanagh** [comment]
Yay, done! Gonna do a small 0.12.1 update later on with this.

If you're using the github branch for this, you'll need to update the blankproject.zip for neko support - like you mention, @azrafe7, you'll need to add `|| neko` to the project.xml for the assets and screensize to get picked up.

Thanks for your help with this, both of you!

**Comment by TerryCavanagh** [comment]
Ok, 0.12.1 is live!
